management:
  endpoints:
    web:
      enabled: true
      base-path: /
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

server:
  port: ${SERVER_PORT:8081}

spring:
  jackson:
    time-zone: UTC
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.yaml
  application:
    name: XFactor Mailer Outbound Adapter
  devtools:
    livereload:
      enabled: false
    remote:
      restart:
        enabled: false
      secret: <redacted>
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:db-operations}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
